### ISSUE TITLE
An error when mix_mode is mixreg

### ISSUE THREAD

**Issue by c4cld** [kaixin96/mixreg#1]
After I running following command:
mpiexec -np 3 python -m train_procgen.train --env_name starpilot --num_levels 500 --mix_mode mixreg --test_worker_interval 1
I got following error report:
Stepping environment...
Traceback (most recent call last):
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'ppo2_model/Placeholder_1' with dtype int32 and shape [?]
     [[{{node ppo2_model/Placeholder_1}} = Placeholder[dtype=DT_INT32, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/train.py", line 158, in <module>
    main()
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/train.py", line 146, in main
    use_l2reg=args.use_l2reg, l2reg_coeff=args.l2reg_coeff),
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/ppo2.py", line 159, in learn
    obs, returns, masks, actions, values, neglogpacs, states, epinfos = runner.run() #pylint: disable=E0632
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/runner.py", line 36, in run
    actions, values, self.states, neglogpacs = self.model.step(self.obs, S=self.states, M=self.dones)
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/rl-generalization/baselines/baselines/common/policies.py", line 93, in step
    a, v, state, neglogp = self._evaluate([self.action, self.vf, self.state, self.neglogp], observation, **extra_feed)
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/rl-generalization/baselines/baselines/common/policies.py", line 75, in _evaluate
    return sess.run(variables, feed_dict)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'ppo2_model/Placeholder_1' with dtype int32 and shape [?]
     [[node ppo2_model/Placeholder_1 (defined at /media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/policy.py:36)  = Placeholder[dtype=DT_INT32, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'ppo2_model/Placeholder_1', defined at:
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/train.py", line 158, in <module>
    main()
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/train.py", line 146, in main
    use_l2reg=args.use_l2reg, l2reg_coeff=args.l2reg_coeff),
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/ppo2.py", line 110, in learn
    max_grad_norm=max_grad_norm, comm=comm, mpi_rank_weight=mpi_rank_weight)
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/model.py", line 27, in model_fn
    return MixregModel(**kwargs)
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/model.py", line 56, in __init__
    act_model = policy(env_name,mix_mode,nbatch_act, 1, sess)
  File "/media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/policy.py", line 36, in policy_fn
    INDICES = tf.placeholder(tf.int32, [None])
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1747, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5206, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/dl_e/anaconda3/envs/RLG-cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'ppo2_model/Placeholder_1' with dtype int32 and shape [?]
     [[node ppo2_model/Placeholder_1 (defined at /media/dl_e/17EF48822800F82E/zjp/code/procgen/mixreg/train_procgen/policy.py:36)  = Placeholder[dtype=DT_INT32, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

The ppo2_model/Placeholder_1 refers to INDICES = tf.placeholder(tf.int32, [None])

**Comment by kaixin96** [comment]
Hi @ZJP-c4cld , the value for placeholder INDICES is fed in this line https://github.com/kaixin96/mixreg/blob/0800f492491f54c5108af9fc13d7c2310cafd0b0/train_procgen/model.py#L230 Are you using the same TF version as in the conda yml files?

By the way, I notice that you are using `--test_worker_interval 1`, which means every worker is a test worker. I am not sure if this is the cause but you can try the scripts in `experiments/README.md` (with `--test_worker_interval 3`).

Feel free to reply if you still encounter any issue. Thank you.

**Comment by c4cld** [comment]
I'm sorry to get back to you so late. I was temporarily assigned to other tasks.  I using the same setting in py36_cu9_tf112.yml. And I try different values when I use --test_worker_interval. But the same problem occurs. In contrast, when I run mixreg/train_procgen/train_dqn.py, this problem does not occur.  Maybe def train() in model.py was not called correctly when I run train.py？

By the way, I have a question about theory. In order to increase both the stability and efficiency of the reinforcement learning process, you apply mixup regularization. But one of the preconditions of using mixup technology is to satisfy independent identically distributed. Do the states and rewards in this article meet the requirements of independent and identically distributed?

I would be very grateful indeed for any help you could give me.

**Comment by c4cld** [comment]
When I search for the keyword "train(" in this repository,  I cannot find the PPO algorithm calling the train function, could you give me some hints about how the PPO algorithm calling the train function?

**Comment by kaixin96** [comment]
`model.train()` is called here https://github.com/kaixin96/mixreg/blob/0800f492491f54c5108af9fc13d7c2310cafd0b0/train_procgen/ppo2.py#L184

Regarding the error, can you try training with a single process (i.e., withou mpi and disable test worker) and see if there is any problem?

Thank you

**Comment by c4cld** [comment]
@kaixin96 Thank you for your prompt reply and selfless help. I try training with a single process(i.e., withou mpi and disable test worker):
python train.py  --env_name starpilot --num_levels 500 --mix_mode mixreg --test_worker_interval 0

Same error occurs.

The error seems to occur at following part in ppo2.py:
"### Get minibatch"
obs, returns, masks, actions, values, neglogpacs, states, epinfos = runner.run()

Thank you

**Comment by kaixin96** [comment]
Can you share the detailed error message? Thank you.

**Comment by c4cld** [comment]
@kaixin96 The detailed error message is in my first comment of this issue. Because the problem then is the same as the problem now. If you need more details, please feel free to talk to me.

Thank you

**Comment by kaixin96** [comment]
If the error occurs in `runner.run()`, then it is related to rollout. For rollout, `act_model` in  is used. https://github.com/kaixin96/mixreg/blob/0800f492491f54c5108af9fc13d7c2310cafd0b0/train_procgen/model.py#L54
So `model.step()` will be called instead of `model.train()`. Since the default argument for `mix_mode` is `no_mix`, the placeholder `INDICES` will not be created.
https://github.com/kaixin96/mixreg/blob/0800f492491f54c5108af9fc13d7c2310cafd0b0/train_procgen/policy.py#L13
Can you check this? Does the act model has this placeholder? Calling `model.step()` should not require feeding `indices`.
My guess at this moment is this might be an issue related to Tensorflow. Hope this helps.

Thank you.

**Comment by c4cld** [comment]
@kaixin96 I try to run train.py in Pycharm and debug step by step. The screenshot is as follows:
![image](https://user-images.githubusercontent.com/19870128/119072152-9e71ad00-ba1d-11eb-919b-8940c40c342a.png)
The placeholder INDICES indeed be created.
![image](https://user-images.githubusercontent.com/19870128/119072319-da0c7700-ba1d-11eb-9478-08442400d74b.png)
In addition, I check the mix_mode. The mix_mode is mixreg rather than nomix.

The error message is :
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'ppo2_model/Placeholder_1' with dtype int32 and shape [?]
[[node ppo2_model/Placeholder_1 

So I guess that the INDICES placeholder is normally created, but no value feeds to the INDICES placeholder. Could you give me some hints about this problem?

Thank you. ^_^

**Comment by kaixin96** [comment]
> In addition, I check the mix_mode. The mix_mode is mixreg rather than nomix.
> So I guess that the INDICES placeholder is normally created, but no value feeds to the INDICES placeholder. Could you give me some hints about this problem?

Yes, you are right. You may check the value feeding part. The value for `INDICES` placeholder should be fed in https://github.com/kaixin96/mixreg/blob/0800f492491f54c5108af9fc13d7c2310cafd0b0/train_procgen/model.py#L230

Thank you.
